Use the correct Jinja tag for homepage_url
Before this change, I was seeing this error when trying to use the template:

Cleaning up...
Traceback (most recent call last):
  File "build.py", line 4, in <module>
    template = Template(template_file.read())
  File "/var/govuk/govuk_template/integration_tests/integrations/jinja/local/lib/python2.7/site-packages/jinja2/environment.py", line 906, in __new__
    return env.from_string(source, template_class=cls)
  File "/var/govuk/govuk_template/integration_tests/integrations/jinja/local/lib/python2.7/site-packages/jinja2/environment.py", line 841, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/var/govuk/govuk_template/integration_tests/integrations/jinja/local/lib/python2.7/site-packages/jinja2/environment.py", line 554, in compile
    self.handle_exception(exc_info, source_hint=source)
  File "/var/govuk/govuk_template/integration_tests/integrations/jinja/local/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<unknown>", line 82, in template
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'homepage_url'.

It should be `{{` and `}}`, instead of `{%` and `%}`. This would make sense
because `html_lang` has used `{{` for some time. Documentation:
http://jinja.pocoo.org/docs/dev/templates/